server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: *****
    url:  jdbc:mysql://*******:3306/yymall?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-timeout: 30000
  redis:
    host: *****
    port: 6379
    password: *****
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  rabbitmq:
    addresses: *****
    port: 5672
    username: admin
    password: *****
  mail:
    username: *****
    password: *****
    host: smtp.exmail.qq.com
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.henu.mall.pojo
  mapper-locations: classpath:mapper/*.xml

#qq
QQ_client_id: ****
QQ_client_secret: ****
QQ_Redirect_uri: ******

#baidu
BaiDu_client_id: *****
BaiDu_client_secret: *****
BaiDu_Redirect_uri: ******

#WeiBo
WeiBo_client_id: ****
WeiBo_client_secret: ****
WeiBo_Redirect_uri: *****

#oss
endpoint: *****
accessKeyId: ******
accessKeySecret: ***
bucketName: ***


#SMS
ZmAccessKeyId: ******
ZmAccessKeySecret: *****
SingName: 智慧药房
TemplateCode: *****


#Courier 快递100
CourierKey: ****
CourierCustomer: ****

#快递鸟
EBusinessID: ***
EKey: ******
